on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Jekyll Site
        working-directory: docs
        run: |
          bundle exec jekyll build

      - name: Temporary Validate Site Folder Created
        run: ls -al _site
