on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Ruby version per https://pages.github.com/versions/
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7

      - name: Build Jekyll Site
        working-directory: docs
        run: |
          bundle install
          bundle exec jekyll build

      - name: Temporary Validate Site Folder Created
        run: ls -al _site
